### ISSUE TITLE
[BUG] Stopped sorting

### ISSUE THREAD

**Issue by bonelifer** [KohGeek/SortYoutubePlaylistByDuration#4]
**Describe the bug**
Stopped sorting a week ago. Says "Sort 3 to 0", but never sorts.

**To Reproduce**
Click sort

**Platform (please complete the following information):**
 - Browser Fireffox
 -- Version 125.0.2
 - Scriptrunner ViolentMonkey
 - Scriptrunner version 2.18.0

**Comment by KohGeek** [comment]
Hi, can you confirm this is still broken?

**Comment by KohGeek** [comment]
Should be fixed in the latest update. Please reopen if there is any issue.
