### ISSUE TITLE
Manual refresh needed to run script when Watch List is opened via YouTube ☰ Menu

### ISSUE THREAD

**Issue by alvinchitena** [KohGeek/SortYoutubePlaylistByDuration#5]
**Platform:** Windows 11 x64
**Browser:** Brave Browser [Version 1.66.118 Chromium: 125.0.6422.147]
**Extension:** Tampermonkey 5.2

When I open the YT Watch List page by opening YouTube dot com, then clicking on Watch List in the ☰ Menu, the script doesn't run. It only runs after a manual page reload. This doesn't happen though if I go directly to the Watch List URL without opening YouTube dot com. I know that this has something to do with "fake navigation," backed up by the following warning I got when I tested the script on Violentmonkey:

![Screenshot 2024-06-04 115508](https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/61254477/f8ed06ae-a5ec-4823-bae2-a8662bb1ac97)
 
I don't mind the reload to run the script, but I was just curious if there is a technical solution to this issue? Thanks for the great script!

**Comment by KohGeek** [comment]
Hi, sorry for the delays, I'm a little swamped in life and work, I'll try to see if I can get this working in the next month.

Seems to me the change is relatively approachable, but you never know, thanks for the report.

**Comment by richardmtl** [comment]
And as of today, the Manual Refresh doesn't work anymore for me on Canary (Mac) : Version 129.0.6628.0 (Official Build) canary (arm64) nor on production Chrome either : Version 127.0.6533.89 (Official Build) (arm64)

**Comment by Shatteredhelix42** [comment]
As of today, the first of August 2024, there's nothing I can do to get the script to work. Direct linking my watch later list, refreshing, nothing is working.  It did work fine yesterday.

Browser version information:
Microsoft Edge
Version 127.0.2651.74 (Official build) (64-bit)
Tampermonkey 5.1.1

**Comment by KohGeek** [comment]
Using VioletMonkey and Edge, I have issues with detecting whether the playlist is fully loaded, but I'm not sure that's the case here for everyone else. In both of your cases is it just it won't start loading at all? Where is the script stuck at?

**Comment by richardmtl** [comment]
I don't know how to answer you exactly. For me, the buttons just don't appear, even after multiple refresh. Let me know what I can do to get you more useful information.

**Comment by KohGeek** [comment]
This seems to be an issue with TamperMonkey again, can you try ViolentMonkey and let me know the results? I'll check on my end when I'm free

**Comment by richardmtl** [comment]
No go. Multiple Refreshes on the WL or other playlist, and no buttons appear.

**Comment by Shatteredhelix42** [comment]
> This seems to be an issue with TamperMonkey again , can you try ViolentMonkey and let me know the results? I'll check on my end when I'm free

Okay, I got it working using Tampermonkey in Firefox. I just sorted an 81-video playlist and had no issues except that I had to use Firefox, not my preferred browser by a long shot. However, it's better than nothing if it'll let me sort videos again.  I still had no luck getting it to work in Edge with either Tampermonkey or Violentmonkey, there just aren't any buttons no matter how many times I refresh.  Everything is up to date.

**Comment by Darkle** [comment]
I get the following error in edge:
```
TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at addCssStyle (Sort Youtube Playlist by Duration.user.js:387:23)
    at Sort Youtube Playlist by Duration.user.js:519:9
    at Sort Youtube Playlist by Duration.user.js:69:17
    at Sort Youtube Playlist by Duration.user.js:39:9
    at NodeList.forEach (<anonymous>)
    at queryForElements (Sort Youtube Playlist by Duration.user.js:36:17)
    at MutationObserver.<anonymous> (Sort Youtube Playlist by Duration.user.js:67:13)
```

TrustedHtml seems to be this: https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML

**Comment by KohGeek** [comment]
> I get the following error in edge:
> ```
> TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
>     at addCssStyle (Sort Youtube Playlist by Duration.user.js:387:23)
>     at Sort Youtube Playlist by Duration.user.js:519:9
>     at Sort Youtube Playlist by Duration.user.js:69:17
>     at Sort Youtube Playlist by Duration.user.js:39:9
>     at NodeList.forEach (<anonymous>)
>     at queryForElements (Sort Youtube Playlist by Duration.user.js:36:17)
>     at MutationObserver.<anonymous> (Sort Youtube Playlist by Duration.user.js:67:13)
> ```
> 
> TrustedHtml seems to be this: https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML

Jackpot find, related to https://github.com/violentmonkey/violentmonkey/issues/1873

I'll try to push up a fix when I'm free in around 6 hours.

**Comment by szebrowski** [comment]
UI works again for me

**Comment by richardmtl** [comment]
Works for me as well! Thank you!

**Comment by KohGeek** [comment]
Added with latest commit

**Comment by alvinchitena** [comment]
I have bad news... The buttons now show up on hot navigation to "Watch List" without refresh, but they don't work. If you click Sort, it scrolls down to the bottom of the page and displays "Loading more videos - x videos loaded." Nothing happens. If you click Sort again, nothing happens.

If you navigate away from the Watch List page, then come back and click Sort, it gets stuck in a loop of "Loading more videos - x videos loaded" and "Playlist not fully loaded, waiting..." In both scenarios, the scroll down to the bottom of the page is persistent, meaning if you try to scroll up, the page keeps scrolling down. Manual refresh fixes everything, as always.

Tested on Brave and Edge with both Tamper and ViolentMonkey. @Shatteredhelix42 can you confirm on your end if this is the behavior?

**Comment by richardmtl** [comment]
@alvinchitena sounds similar to my #7 . Note that for me, the buttons DO work as expected on my Watchlist https://www.youtube.com/playlist?list=WL

**Comment by KohGeek** [comment]
Youtube broke the way I detect the end of loading, so I gotta come up with a new way, but this is unrelated to this change, should be #7 and #6 both.

**Comment by Shatteredhelix42** [comment]
@alvinchitena I have had this exact behavior in the past, and the workaround I have found is to scroll down all the way to the bottom of the list first and make sure all of the thumbnails load, then you can scroll back up to the top and hit the button with no issues.

**Comment by alvinchitena** [comment]
@richardmtl Do you navigate directly to the YT Watch Later URL? If you do, that counts as a "manual refresh," as the browser loads the WL page from scratch, as opposed to the "hot navigation" Single-Page Application magic it does otherwise, e.g. open YT Homepage then click Watch Later. It's either that or something to do with you being on macOS instead of Win 11.

@Shatteredhelix42 I tried your suggestion, and it doesn't work (anymore). Switching to "Sort only loaded" and scrolling to the bottom doesn't change the behavior for me. Hopefully it's all just related to the end of loading detection issue and will be fixed when that's solved.

**Comment by KohGeek** [comment]
My code, albeit edited, is working with hot navigation. So let's see if the WIP update will fix everything

**Comment by alvinchitena** [comment]
The latest version of the script (3.1.0) works on all playlists. Buttons load on hot navigation and sort works without manual refresh. Test on Brave and Chrome Canary Browser. Your commit notes suggest you will continue to work on it. I'll try my best to promptly provide feedback on any changes you make. Thank you very much for your effort @KohGeek.
